<?php
	define( 'PAFE_FEATURES_FREE', json_encode( array(
			array(
				'name' => __('Gradient Text','pafe'),
				'option' => 'pafe-features-gradient-text',
				'url' => 'https://pafe.piotnet.com/docs/gradient-text-gradient-button/?wpam_id=1',
				'pro' => false,
			),
			array(
				'name' => __('Gradient Button','pafe'),
				'option' => 'pafe-features-gradient-button',
				'url' => 'https://pafe.piotnet.com/docs/gradient-text-gradient-button/?wpam_id=1',
				'pro' => false,
			),
			array(
				'name' => __('Image Carousel Multiple Custom Urls','pafe'),
				'option' => 'pafe-features-image-carousel-multiple-custom-urls',
				'url' => 'https://pafe.piotnet.com/docs/image-carousel-multiple-custom-urls/?wpam_id=1',
				'pro' => false,
				'extension' => true,
			),
			array(
				'name' => __('Before After Image Comparison Slider','pafe'),
				'option' => 'pafe-features-before-after-image-comparison-slider',
				'url' => 'https://pafe.piotnet.com/docs/before-after-image-comparison-slider/?wpam_id=1',
				'pro' => false,
				'widget' => true,
			),
			array(
				'name' => __('Switch Content','pafe'),
				'option' => 'pafe-features-switch-content',
				'url' => 'https://pafe.piotnet.com/docs/switch-content/?wpam_id=1',
				'pro' => false,
				'widget' => true,
			),
			array(
				'name' => __('Tooltip','pafe'),
				'option' => 'pafe-features-tooltip',
				'url' => 'https://pafe.piotnet.com/docs/tooltip/?wpam_id=1',
				'pro' => false,
				'extension' => true,
			),
			array(
				'name' => __('Video Playlist','pafe'),
				'option' => 'pafe-features-video-playlist',
				'url' => 'https://pafe.piotnet.com/docs/video-playlist/?wpam_id=1',
				'pro' => false,
				'widget' => true,
			), 
			array(
				'name' => __('Vertical Timeline','pafe'),
				'option' => 'pafe-features-vertical-timeline',
				'url' => 'https://pafe.piotnet.com/docs/vertical-timeline/?wpam_id=1',
				'pro' => false,
				'widget' => true,
			),
			array(
				'name' => __('Image Accordion','pafe'),
				'option' => 'pafe-features-image-accordion',
				'url' => 'https://pafe.piotnet.com/docs/image-accordion/?wpam_id=1',
				'pro' => false,
				'widget' => true,
			), 
			array(
				'name' => __('Posts List','pafe'),
				'option' => 'pafe-features-posts-list',
				'url' => 'https://pafe.piotnet.com/docs/posts-list/?wpam_id=1',
				'pro' => false,
				'widget' => true, 
			),
			array(
				'name' => __('Sales Pop','pafe'), 
				'option' => 'pafe-features-sales-pop',
				'url' => 'https://pafe.piotnet.com/docs/sales-pop/?wpam_id=1',
				'pro' => false,
				'widget' => true,
			),
			array(
				'name' => __('Countdown Cart','pafe'),
				'option' => 'pafe-features-countdown-cart',
				'url' => 'https://pafe.piotnet.com/docs/countdown-cart/?wpam_id=1',
				'pro' => false,
				'widget' => true, 
			),
			array(
				'name' => __('Dual Color Headline','pafe'),
				'option' => 'pafe-features-dual-color-headline',
				'url' => 'https://pafe.piotnet.com/docs/dual-color-headline/?wpam_id=1',
				'pro' => false,
				'widget' => true, 
			),
			array(
				'name' => __('Form Style','pafe'),
				'option' => 'pafe-features-form-style',
				'url' => 'https://pafe.piotnet.com/docs/form-style/?wpam_id=1',
				'pro' => false,
				'extension' => true,
			),
			array(
				'name' => __('Hotspot','pafe'),
				'option' => 'pafe-features-hotspot',
				'url' => 'https://pafe.piotnet.com/docs/hotspot/?wpam_id=1',
				'pro' => false,
				'widget' => true, 
			),
			array(
				'name' => __('Particles','pafe'),
				'option' => 'pafe-features-particles',
				'url' => 'https://pafe.piotnet.com/docs/particles/?wpam_id=1',
				'pro' => false,
				'extension' => true,
			),
			array(
				'name' => __('Progress Bar','pafe'),
				'option' => 'pafe-features-progressbar',
				'url' => 'https://pafe.piotnet.com/docs/progress-bar/?wpam_id=1',
				'pro' => false,
				'widget' => true, 
			),
			array(
				'name' => __('Table','pafe'),
				'option' => 'pafe-features-table',
				'url' => 'https://pafe.piotnet.com/docs/table/?wpam_id=1',
				'pro' => false,
				'widget' => true, 
			),
		) )
	);

	define( 'PAFE_FEATURES_PRO', json_encode( array(
			array(
				'name' => __('Custom Media Query Breakpoints','pafe'),
				'option' => 'pafe-features-custom-media-query-breakpoints',
				'url' => 'https://pafe.piotnet.com/docs/custom-media-query-breakpoints/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Equal Height','pafe'),
				'option' => 'pafe-features-equal-height',
				'url' => 'https://pafe.piotnet.com/docs/equal-height/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Equal Height For CTA','pafe'),
				'option' => 'pafe-features-equal-height-for-cta',
				'url' => 'https://pafe.piotnet.com/docs/equal-height/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Equal Height For Woocommerce Products','pafe'),
				'option' => 'pafe-features-equal-height-for-woocommerce-products',
				'url' => 'https://pafe.piotnet.com/docs/equal-height/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Column Width ( Pixel, %, calc )','pafe'),
				'option' => 'pafe-features-column-width',
				'url' => 'https://pafe.piotnet.com/docs/column-width-pixel-calc/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Responsive Border Width','pafe'),
				'option' => 'pafe-features-responsive-border-width',
				'url' => 'https://pafe.piotnet.com/?wpam_id=1#responsive-border-width',
				'pro' => 1,
			),
			array(
				'name' => __('Responsive Background','pafe'),
				'option' => 'pafe-features-responsive-background',
				'url' => 'https://pafe.piotnet.com/docs/responsive-background-color/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Multiple Background Images','pafe'),
				'option' => 'pafe-features-multiple-background-images',
				'url' => 'https://pafe.piotnet.com/docs/multiple-background-images/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Absolute Positioning','pafe'),
				'option' => 'pafe-features-absolute-positioning',
				'url' => 'https://pafe.piotnet.com/?wpam_id=1#absolute-positioning',
				'pro' => 1,
			),
			array(
				'name' => __('Display Inline Block','pafe'),
				'option' => 'pafe-features-display-inline-block',
				'url' => 'https://pafe.piotnet.com/?wpam_id=1#display-inline-block',
				'pro' => 1,
			),
			array(
				'name' => __('Section Link','pafe'),
				'option' => 'pafe-features-section-link',
				'url' => 'https://pafe.piotnet.com/docs/section-link-column-link/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Column Link','pafe'),
				'option' => 'pafe-features-column-link',
				'url' => 'https://pafe.piotnet.com/docs/section-link-column-link/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Max Width','pafe'),
				'option' => 'pafe-features-max-width',
				'url' => 'https://pafe.piotnet.com/?wpam_id=1#max-width',
				'pro' => 1,
			),
			array(
				'name' => __('Parallax Background','pafe'),
				'option' => 'pafe-features-parallax-background',
				'url' => 'https://pafe.piotnet.com/docs/parallax-background-for-every-element/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Responsive Column Order','pafe'),
				'option' => 'pafe-features-responsive-column-order',
				'url' => 'https://pafe.piotnet.com/docs/responsive-column-order/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Responsive Hide Column','pafe'),
				'option' => 'pafe-features-responsive-hide-column',
				'url' => 'https://pafe.piotnet.com/?wpam_id=1#responsive-hide-column',
				'pro' => 1,
			),
			array(
				'name' => __('Font Awesome 5','pafe'),
				'option' => 'pafe-features-font-awesome-5',
				'url' => 'https://pafe.piotnet.com/?wpam_id=1#font-awesome-5',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Navigation Arrows Icon','pafe'),
				'option' => 'pafe-features-navigation-arrows-icon',
				'url' => 'https://pafe.piotnet.com/docs/navigation-arrows-icon-and-advanced-dots-styling-for-slides-and-image-carousel-widget/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Lightbox Image','pafe'),
				'option' => 'pafe-features-lightbox-image',
				'url' => 'https://pafe.piotnet.com/docs/lightbox-gallery-masonry-with-title-and-caption-thumbnail-custom-size/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Lightbox Garllery Masonry','pafe'),
				'option' => 'pafe-features-lightbox-gallery',
				'url' => 'https://pafe.piotnet.com/docs/lightbox-gallery-masonry-with-title-and-caption-thumbnail-custom-size/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Responsive Gallery Column Width','pafe'),
				'option' => 'pafe-features-responsive-gallery-column-width',
				'url' => 'https://pafe.piotnet.com/docs/lightbox-gallery-masonry-with-title-and-caption-thumbnail-custom-size/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Responsive Gallery Images Spacing','pafe'),
				'option' => 'pafe-features-responsive-gallery-images-spacing',
				'url' => 'https://pafe.piotnet.com/docs/lightbox-gallery-masonry-with-title-and-caption-thumbnail-custom-size/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Media Carousel Aspect Ratio','pafe'),
				'option' => 'pafe-features-media-carousel-ratio',
				'url' => 'https://pafe.piotnet.com/docs/media-carousel-ratio/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Advanced Form Styling','pafe'),
				'option' => 'pafe-features-advanced-form-styling',
				'url' => 'https://pafe.piotnet.com/docs/advanced-form-styling/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Advanced Tabs Styling','pafe'),
				'option' => 'pafe-features-advanced-tabs-styling',
				'url' => 'https://pafe.piotnet.com/docs/advanced-tabs-styling/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Advanced Dots Styling','pafe'),
				'option' => 'pafe-features-advanced-dots-styling',
				'url' => 'https://pafe.piotnet.com/docs/navigation-arrows-icon-and-advanced-dots-styling-for-slides-and-image-carousel-widget/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Responsive Section Column Text Align','pafe'),
				'option' => 'pafe-features-responsive-section-column-text-align',
				'url' => 'https://pafe.piotnet.com/docs/responsive-section-column-text-align/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Close First Accordion','pafe'),
				'option' => 'pafe-features-close-first-accordion',
				'url' => 'https://pafe.piotnet.com/docs/close-first-accordion/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Column Aspect Ratio','pafe'),
				'option' => 'pafe-features-column-aspect-ratio',
				'url' => 'https://pafe.piotnet.com/docs/column-aspect-ratio/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Slider Builder','pafe'),
				'option' => 'pafe-features-slider-builder',
				'url' => 'https://pafe.piotnet.com/docs/slider-builder-with-animation/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Popup Trigger URL','pafe'),
				'option' => 'pafe-features-popup-trigger-url',
				'url' => 'https://pafe.piotnet.com/docs/popup-trigger-url/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Advanced Nav Menu Styling','pafe'),
				'option' => 'pafe-features-advanced-nav-menu-styling',
				'url' => 'https://pafe.piotnet.com/docs/advanced-nav-menu-styling-custom-toggle-image-dropdown-absolute/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Toggle Content','pafe'),
				'option' => 'pafe-features-toggle-content',
				'url' => 'https://pafe.piotnet.com/docs/toggle-content-readmore-content/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Scroll Box With Custom Scrollbar','pafe'),
				'option' => 'pafe-features-scroll-box-with-custom-scrollbar',
				'url' => 'https://pafe.piotnet.com/docs/scroll-box-with-custom-scrollbar/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Ajax Live Search','pafe'),
				'option' => 'pafe-features-ajax-live-search',
				'url' => 'https://pafe.piotnet.com/docs/ajax-live-search/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Crossfade Multiple Background Images','pafe'),
				'option' => 'pafe-features-crossfade-multiple-background-images',
				'url' => 'https://pafe.piotnet.com/docs/crossfade-multiple-background-images/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Form Builder','pafe'),
				'option' => 'pafe-features-form-builder',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
				'form-builder' => true,
			),
			array(
				'name' => __('Woocommerce Checkout','pafe'),
				'option' => 'pafe-features-woocommerce-checkout',
				'url' => 'https://pafe.piotnet.com/docs/woocommerce-sales-funnel/?wpam_id=1',
				'pro' => 1,
				'woocommerce_sales_funnels' => true,
			),
			array(
				'name' => __('Conditional Logic Form','pafe'),
				'option' => 'pafe-features-conditional-logic-form',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('PAFE Form Builder Conditional Logic','pafe'),
				'option' => 'pafe-features-form-builder-conditional-logic',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Calculated Fields Form','pafe'),
				'option' => 'pafe-features-calculated-fields-form',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Range Slider Field','pafe'),
				'option' => 'pafe-features-range-slider',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Image Select Field','pafe'),
				'option' => 'pafe-features-image-select-field',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Signature Field','pafe'),
				'option' => 'pafe-features-signature-field',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Select Autocomplete Field','pafe'),
				'option' => 'pafe-features-select-autocomplete-field',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Address Autocomplete Field','pafe'),
				'option' => 'pafe-features-address-autocomplete-field',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Connect Form to Google Sheets','pafe'),
				'option' => 'pafe-features-form-google-sheets-connector',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('Multi Step Form','pafe'),
				'option' => 'pafe-features-multi-step-form',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Stripe Payment','pafe'),
				'option' => 'pafe-features-stripe-payment',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Submit Post','pafe'),
				'option' => 'pafe-features-submit-post',
				'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Responsive Custom Positioning','pafe'),
				'option' => 'pafe-features-responsive-custom-positioning',
				'url' => 'https://pafe.piotnet.com/docs/responsive-custom-positioning/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Conditional Visibility','pafe'),
				'option' => 'pafe-features-conditional-visibility',
				'url' => 'https://pafe.piotnet.com/docs/conditional-visibility/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Text Color Change on Column Hover','pafe'),
				'option' => 'pafe-features-text-color-change-on-column-hover',
				'url' => 'https://pafe.piotnet.com/docs/text-color-change-on-column-hover/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Css Filters','pafe'),
				'option' => 'pafe-features-css-filters',
				'url' => 'https://pafe.piotnet.com/docs/css-filters-for-any-widgets-section-column/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Convert Image To Black Or White','pafe'),
				'option' => 'pafe-features-convert-image-to-black-or-white',
				'url' => 'https://pafe.piotnet.com/docs/convert-image-to-black-or-white/?wpam_id=1',
				'pro' => 1,
			),
			array(
				'name' => __('Sticky Header','pafe'),
				'option' => 'pafe-features-sticky-header',
				'url' => 'https://pafe.piotnet.com/docs/sticky-header/?wpam_id=1',
				'pro' => 1,
				'extension' => true,
			),
			array(
				'name' => __('WooCommerce Sales Funnel','pafe'),
				'option' => 'pafe-features-woocommerce-sales-funnel',
				'url' => 'https://pafe.piotnet.com/docs/woocommerce-sales-funnel/?wpam_id=1',
				'pro' => 1,
				'woocommerce_sales_funnels' => true,
			),
		) )
	);
?>